### ISSUE TITLE
Suggestion: don't use spaces between words when adding awesome item

### ISSUE THREAD

**Issue by avalynndev** [birobirobiro/awesome-shadcn-ui#103]
When adding an awesome item. for example cv forge, instead of keeping [CV forge](). can't we keep [cv-forge]() that way every item in the repository will follow a pattern which would look cool.. imo

**Comment by avalynndev** [comment]
@birobirobiro ?

**Comment by birobirobiro** [comment]
Can you send a PR fixing this?

**Comment by birobirobiro** [comment]
https://github.com/birobirobiro/awesome-shadcn-ui/commit/fae51f2d51953a6bdde4970651f7d18362e389d0

**Comment by avalynndev** [comment]
Thx my guy
