### ISSUE TITLE
Bug: project with no relation with shadcn

### ISSUE THREAD

**Issue by avalynndev** [birobirobiro/awesome-shadcn-ui#124]
In commit https://github.com/birobirobiro/awesome-shadcn-ui/pull/122, the project https://github.com/shubh73/devfolio doesnt show any clear relation with shadcn at all. This being a awesome-shadcn-ui repository shouldn't it be related to shadcn ui?
@birobirobiro @shubh73

**Comment by shubh73** [comment]
@avalynndev [devfolio](shubhporwal.me) directly uses components from [aceternity-ui](https://ui.aceternity.com/) and  [magicui](https://magicui.design/), both of which are based on shadcn/ui. Additionally, there's also a pending PR that directly incorporates shadcn/ui components. Once merged, the connection to shadcn/ui should be clearer.
