### ISSUE TITLE
Add Inspira UI (Vue)

### ISSUE THREAD

**Issue by KyleSmith0905** [birobirobiro/awesome-shadcn-ui#131]
Found "Inspira UI" on X, wanted to drop it here. I don't know how it would be done categorically... It's not a "Vue port", it's different components.

Here it is: https://inspira-ui.com/components/all

**Comment by avalynndev** [comment]
Hey @KyleSmith0905.. pretty sure it will come under the Lib & Components Section as it is very similar to Aceternity UI. I will create a pr to add this change so you may close this issue

> and not related to the issue.. how have you been.. you might know me as plusflippy, long time no see mg

**Comment by avalynndev** [comment]
Added can close issue @birobirobiro
