### ISSUE TITLE
Add Shadcn-Form Builder

### ISSUE THREAD

**Issue by Mykel68** [birobirobiro/awesome-shadcn-ui#150]
Build Shadcn Forms Faster with zod and react-hook-form within minutes

the url is https://www.shadcn-form.com/

**Comment by birobirobiro** [comment]
https://github.com/birobirobiro/awesome-shadcn-ui/blob/71d69be9bc9b4d38b9f8dd7d860ac43319959c26/README.md?plain=1#L187C25-L187C62
