### ISSUE TITLE
Feature: Provide option to group free and paid resources.

### ISSUE THREAD

**Issue by vihaan-that** [birobirobiro/awesome-shadcn-ui#156]
I would like to suggest a feature to show which resources are paid and which are free from this repo. I believe it would be useful for developers who are short of change and need something in the nick of time. If accepted, I am willing to send a PR to enable this.

**Comment by birobirobiro** [comment]
The idea behind this repository is to gather free resources. I know some offer plans, but there's always a free plan as well. So I don't think it makes much sense, do you agree?

**Comment by JugglerX** [comment]
I had my submission rejected. It was a resource that is both free and paid. I get why it was rejected. But Its also frustrating to see many other projects that are both free and paid get approved. In some cases people are flipping their free projects to paid after the fact. I kinda feel like I got unlucky with my submission, it feels a little arbitrary that i was declined.

So perhaps a policy that groups by free/paid/freemium would actually be fairer, and overall more useful? Plenty of people are willing to pay for resources, and some paid resources are good value.

**Comment by birobirobiro** [comment]
> I had my submission rejected. It was a resource that is both free and paid. I get why it was rejected. But Its also frustrating to see many other projects that are both free and paid get approved. In some cases people are flipping their free projects to paid after the fact. I kinda feel like I got unlucky with my submission, it feels a little arbitrary that i was declined.
> 
> So perhaps a policy that groups by free/paid/freemium would actually be fairer, and overall more useful? Plenty of people are willing to pay for resources, and some paid resources are good value.

The repository layout has been reorganized, making it easier to navigate through different categories. If you'd like, you're welcome to create a new category that fits your submission and add your resource there. This way, we can ensure the repository remains well-organized and inclusive for all types of contributions.
