### ISSUE TITLE
A better separation for viewing new links

### ISSUE THREAD

**Issue by guibzo** [birobirobiro/awesome-shadcn-ui#189]
Hey there.
I often come to this repo to find some great things ready to use or to take some inspiration off.
Notice the word "often".
Everytime I return in here, I have to manually go through the commits to see what's new.

That's terrible and time consuming. Not only I have to check for actual links that interest me, but I have to copy the links and paste it on the browser every time instead of copying them (because of MDX syntax).
Also, there is no easy way to tell where I stopped last time.

My suggestion is pretty simple: Add or a update note according to month or something, or in the project description separate it by putting last added items first.
It would be a far greater experience.

Overall, nice repo biro & nice work for the people that go out there mining those in the deepens of the JS weird ecossystem.

**Comment by birobirobiro** [comment]
Thank you for your feedback, @guibzo!  

The repository has been updated with tables to make browsing and finding links much easier. Additionally, we’ll start adding update notes moving forward to improve the overall experience and help you track what’s new more effectively.  

We appreciate your suggestion and hope the updates enhance your experience! 🚀
