### ISSUE TITLE
Add Rangeen

### ISSUE THREAD

**Issue by navjotahuja92** [birobirobiro/awesome-shadcn-ui#23]
Not sure whether this fits or not
I have one for Colors and Customizations which uses **Material Colors algorithm**

https://navnote.github.io/rangeen/
https://github.com/navnote/rangeen

**Comment by birobirobiro** [comment]
Done ✅

https://github.com/birobirobiro/awesome-shadcn-ui/commit/fc9abd8d27545fe1f1189c66cdad4861e33844ff
