### ISSUE TITLE
Add shadcn-tw-plugin

### ISSUE THREAD

**Issue by blazeshomida** [birobirobiro/awesome-shadcn-ui#30]
Not sure if this is good enough, but I created a plugin that helps with theming in shadcn. It's on npm as shadcn-tw-plugin. I have another one that also has support for theming shadcn, but not necessarily specifically for shadcn, more so general tailwind theming however both should work with and without shadcn. The other one if interested is @twilightcss/twilightcss on npm.

**Comment by birobirobiro** [comment]
> Not sure if this is good enough, but I created a plugin that helps with theming in shadcn. It's on npm as shadcn-tw-plugin. I have another one that also has support for theming shadcn, but not necessarily specifically for shadcn, more so general tailwind theming however both should work with and without shadcn. The other one if interested is @twilightcss/twilightcss on npm.

If you prefer, you can add this plugin to the list, which I think makes more sense. Add in the [Plugins and Extensions](https://github.com/birobirobiro/awesome-shadcn-ui?tab=readme-ov-file#plugins-and-extensions) section
