### ISSUE TITLE
Request for Links to Open in New Page?

### ISSUE THREAD

**Issue by ajay-er** [birobirobiro/awesome-shadcn-ui#43]
Hello! 👋 I noticed that in the README.md file, the links open on the same page. Could we update them to open in a new tab or window? It would improve user experience and make navigation smoother.

We can achieve this by adding target="_blank" attribute to the anchor tags in the README.md file.

 Thanks!

**Comment by birobirobiro** [comment]
> Hello! 👋 I noticed that in the README.md file, the links open on the same page. Could we update them to open in a new tab or window? It would improve user experience and make navigation smoother.
> 
> We can achieve this by adding target="_blank" attribute to the anchor tags in the README.md file.
> 
> Thanks!

Even if you added the target="_blank" anchor tags, it would not have that functionality. You can check for yourself on this line here; it has been added and still opens on the same page.

https://github.com/birobirobiro/awesome-shadcn-ui/blob/main/README.md?plain=1#L11

**Comment by birobirobiro** [comment]
> > Hello! 👋 I noticed that in the README.md file, the links open on the same page. Could we update them to open in a new tab or window? It would improve user experience and make navigation smoother.
> > We can achieve this by adding target="_blank" attribute to the anchor tags in the README.md file.
> > Thanks!
> 
> Even if you added the target="_blank" anchor tags, it would not have that functionality. You can check for yourself on this line here; it has been added and still opens on the same page.
> 
> https://github.com/birobirobiro/awesome-shadcn-ui/blob/main/README.md?plain=1#L11

Alternatively, you can use the site I created that parses this README into HTML.

https://awesome-shadcn-ui.vercel.app/

**Comment by ajayyAI** [comment]
Thank you for the clarification. I understand that target="_blank" doesn't work in the README.md. The alternative site you provided is helpful.

Thanks!
