### ISSUE TITLE
Suggestion : Add "Added Date" to Items in the List

### ISSUE THREAD

**Issue by Thesmit113** [birobirobiro/awesome-shadcn-ui#55]
Hi, It would be great if each item in the list had an "added date" or something to help users identify newly added items.

Thanks!

**Comment by birobirobiro** [comment]
> Hi, It would be great if each item in the list had an "added date" or something to help users identify newly added items.
> 
> Thanks!

Any suggestions on how I could do this other than putting all the data from the README in a table?

**Comment by Ardian-Hoti** [comment]
> > Hi, It would be great if each item in the list had an "added date" or something to help users identify newly added items.
> > Thanks!
> 
> Any suggestions on how I could do this other than putting all the data from the README in a table?

I guess just put the current date you are adding the new links , in the end of the text  just put - 2024-06-30 for example or different date format doesnt matter , I think this is okay

**Comment by Thesmit113** [comment]
we can add the date as a badge or tag at the end of each item line:

[aceternity-ui](https://ui.aceternity.com/) - Copy paste the most trending react components without having to worry about styling and animations. ![Added on 2024-06-30](https://img.shields.io/badge/added-2024--06--30-brightgreen)

**Comment by Ardian-Hoti** [comment]
> we can add the date as a badge or tag at the end of each item line:
> 
> [aceternity-ui](https://ui.aceternity.com/) - Copy paste the most trending react components without having to worry about styling and animations. ![Added on 2024-06-30](https://img.shields.io/badge/added-2024--06--30-brightgreen)
> 

Yeah, that's better

**Comment by birobirobiro** [comment]
> we can add the date as a badge or tag at the end of each item line:
> 
> [aceternity-ui](https://ui.aceternity.com/) - Copy paste the most trending react components without having to worry about styling and animations. ![Added on 2024-06-30](https://camo.githubusercontent.com/fcf7cf3645552f695e3bda498793afd6d71cbe7f5321d985157c7905f86c7d9e/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f61646465642d323032342d2d30362d2d33302d627269676874677265656e)

This is great idea solution

**Comment by Ardian-Hoti** [comment]
> > we can add the date as a badge or tag at the end of each item line:
> > [aceternity-ui](https://ui.aceternity.com/) - Copy paste the most trending react components without having to worry about styling and animations. ![Added on 2024-06-30](https://camo.githubusercontent.com/fcf7cf3645552f695e3bda498793afd6d71cbe7f5321d985157c7905f86c7d9e/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f61646465642d323032342d2d30362d2d33302d627269676874677265656e)
> 
> This is great idea solution

so is this gonna be the last option and you'll do this ? I like it

**Comment by anishshobithps** [comment]
> we can add the date as a badge or tag at the end of each item line:
> 
> [aceternity-ui](https://ui.aceternity.com/) - Copy paste the most trending react components without having to worry about styling and animations. ![Added on 2024-06-30](https://camo.githubusercontent.com/fcf7cf3645552f695e3bda498793afd6d71cbe7f5321d985157c7905f86c7d9e/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f61646465642d323032342d2d30362d2d33302d627269676874677265656e)

This is a great idea but I still think it might be hard to spot latest ones with respect to dates.

New ones can simply shown with a different badge as ![NEW](https://img.shields.io/badge/-NEW-61DAFB)
instead of Date, make it more easy for people to spot new ones and when a new PR is merged the action will remove `NEW` and replace with the Date format above as per commit history.

`![NEW](https://img.shields.io/badge/-NEW-61DAFB)`, you can adjust colors and all on shields.io site

**Comment by birobirobiro** [comment]
> > we can add the date as a badge or tag at the end of each item line:
> > [aceternity-ui](https://ui.aceternity.com/) - Copy paste the most trending react components without having to worry about styling and animations. ![Added on 2024-06-30](https://camo.githubusercontent.com/fcf7cf3645552f695e3bda498793afd6d71cbe7f5321d985157c7905f86c7d9e/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f61646465642d323032342d2d30362d2d33302d627269676874677265656e)
> 
> This is a great idea but I still think it might be hard to spot latest ones with respect to dates.
> 
> New ones can simply shown with a different badge as ![NEW](https://camo.githubusercontent.com/352a3febf47282b7f093e9522e2192d279235feaaa70c59e31063cf82972a3e3/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f2d4e45572d363144414642) instead of Date, make it more easy for people to spot new ones and when a new PR is merged the action will remove `NEW` and replace with the Date format above as per commit history.
> 
> `![NEW](https://img.shields.io/badge/-NEW-61DAFB)`, you can adjust colors and all on shields.io site

This way it would be better to identify it, but would it be up to whoever created the PR to add this badge or would it be easier for me to add it by hand whenever a new PR appears?

**Comment by anishshobithps** [comment]
> > > we can add the date as a badge or tag at the end of each item line:
> > > [aceternity-ui](https://ui.aceternity.com/) - Copy paste the most trending react components without having to worry about styling and animations. ![Added on 2024-06-30](https://camo.githubusercontent.com/fcf7cf3645552f695e3bda498793afd6d71cbe7f5321d985157c7905f86c7d9e/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f61646465642d323032342d2d30362d2d33302d627269676874677265656e)
> > 
> > 
> > This is a great idea but I still think it might be hard to spot latest ones with respect to dates.
> > New ones can simply shown with a different badge as ![NEW](https://camo.githubusercontent.com/352a3febf47282b7f093e9522e2192d279235feaaa70c59e31063cf82972a3e3/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f2d4e45572d363144414642) instead of Date, make it more easy for people to spot new ones and when a new PR is merged the action will remove `NEW` and replace with the Date format above as per commit history.
> > `![NEW](https://img.shields.io/badge/-NEW-61DAFB)`, you can adjust colors and all on shields.io site
> 
> This way it would be better to identify it, but would it be up to whoever created the PR to add this badge or would it be easier for me to add it by hand whenever a new PR appears?

If there was some CI/CD for this it would have been better but I think that can be left to you if you wish to add it or the person creating the PR, before merging you can ask the person creating the PR to add the change, I'll try looking into making a CI/CD pipeline if possible next week.

**Comment by birobirobiro** [comment]
Thanks for the suggestion, but I think the README layout wouldn't look very nice. If it were a table it would make sense as it is on the site today.

**Comment by birobirobiro** [comment]
Thanks for the suggestion, but I think the README layout wouldn't look very nice. If it were a table it would make sense as it is on the site today.

**Comment by birobirobiro** [comment]
> > > > we can add the date as a badge or tag at the end of each item line:
> > > > [aceternity-ui](https://ui.aceternity.com/) - Copy paste the most trending react components without having to worry about styling and animations. ![Added on 2024-06-30](https://camo.githubusercontent.com/fcf7cf3645552f695e3bda498793afd6d71cbe7f5321d985157c7905f86c7d9e/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f61646465642d323032342d2d30362d2d33302d627269676874677265656e)
> > > 
> > > 
> > > This is a great idea but I still think it might be hard to spot latest ones with respect to dates.
> > > New ones can simply shown with a different badge as ![NEW](https://camo.githubusercontent.com/352a3febf47282b7f093e9522e2192d279235feaaa70c59e31063cf82972a3e3/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f2d4e45572d363144414642) instead of Date, make it more easy for people to spot new ones and when a new PR is merged the action will remove `NEW` and replace with the Date format above as per commit history.
> > > `![NEW](https://img.shields.io/badge/-NEW-61DAFB)`, you can adjust colors and all on shields.io site
> > 
> > 
> > This way it would be better to identify it, but would it be up to whoever created the PR to add this badge or would it be easier for me to add it by hand whenever a new PR appears?
> 
> If there was some CI/CD for this it would have been better but I think that can be left to you if you wish to add it or the person creating the PR, before merging you can ask the person creating the PR to add the change, I'll try looking into making a CI/CD pipeline if possible next week.

If we add this New badge, how could we make it disappear after a while and how long would that be? What would the README layout look like?

About the README layout I thought of something like this, what do you think?

![image](https://github.com/user-attachments/assets/f7ff4598-66b9-4a24-965f-62ee92a3bd35)
---
![image](https://github.com/user-attachments/assets/7739bb16-7ca1-4640-9a3c-86b8f3154bc8)
