### ISSUE TITLE
Add Jolly UI

### ISSUE THREAD

**Issue by KyleSmith0905** [birobirobiro/awesome-shadcn-ui#6]
https://www.jollyui.dev

Don't know who they are; just know they exist. It's shadcn/ui remade in React Aria

**Comment by birobirobiro** [comment]
> https://www.jollyui.dev
> 
> Don't know who they are; just know they exist. It's shadcn/ui remade in React Aria

Thanks for the suggestion, already added in the README

https://github.com/birobirobiro/awesome-shadcn-ui/blob/main/README.md?plain=1#L74
