### ISSUE TITLE
add Spartan NG

### ISSUE THREAD

**Issue by KyleSmith0905** [birobirobiro/awesome-shadcn-ui#7]
I've used them for a project. It's a shadcn/ui port in Angular. Since there's no competition for component libraries in Angular, spartan.ng really shines in Angular.

**Comment by birobirobiro** [comment]
Thanks for the tip, I didn't know that one. I will add it to the ports category

https://github.com/birobirobiro/awesome-shadcn-ui/blob/63a3f1fcaa48ee14a601cae3f3aa69f6c7991c7b/README.md?plain=1#L71
