### ISSUE TITLE
A collab on new list

### ISSUE THREAD

**Issue by avalynndev** [birobirobiro/awesome-shadcn-ui#76]
I'm thinking of creating a list for awesome shadcn-ui list for open source projects, is it possible if we can collab on it ?

**Comment by avalynndev** [comment]
this is the data I fetched (30m work real): https://github.com/avalynndev/awesome-shadcn-projects

**Comment by birobirobiro** [comment]
> this is the data I fetched (30m work real): https://github.com/avalynndev/awesome-shadcn-projects

How is my list different from what exists today? I didn't understand

**Comment by avalynndev** [comment]
My list is a list of open source projects that used shadcn tools and stuf and built on top of that
your list is tools, templates etc. mostly

**Comment by birobirobiro** [comment]
> My list is a list of open source projects that used shadcn tools and stuf and built on top of that your list is tools, templates etc. mostly

It doesn't make sense since all of these projects are on my list.
