### ISSUE TITLE
Suggestion : Add "shadcn-theme-editor"

### ISSUE THREAD

**Issue by programming-with-ia** [birobirobiro/awesome-shadcn-ui#93]
[![NPM Version](https://img.shields.io/npm/v/shadcn-theme-editor?logo=npm)](https://www.npmjs.com/package/shadcn-theme-editor)
[![GitHub](https://img.shields.io/badge/shadcn_theme_editor-161b22?logo=github)](https://github.com/programming-with-ia/shadcn-theme-editor)

**Comment by DavidODonovan** [comment]
Hi, I've just tested this component in my local Next.js app and sadly it simply doesnt work as expected. After installation the menu of buttons appears on the left hand side, but picking colours does not update the colours in the UI, even after manually refreshing the page. It's a great idea, but not working for me.

**Comment by programming-with-ia** [comment]
@DavidODonovan  i tested it it is working
check out [`layout.tsx`](https://github.com/programming-with-ia/shadcn-theme-editor/blob/7d1f803615be1461f2f13de18d11c850585401b4/app/src/app/layout.tsx)
or [demo](https://shadcnthemeeditor.vercel.app/) 
try again latest v1.0.0
it's working

**Comment by programming-with-ia** [comment]
Which version u use
Try v1.0.0
check for more info Github reply<https://github.com/birobirobiro/awesome-shadcn-ui/issues/93>
[https://opengraph.githubassets.com/5190c8919ab50155d2c1298e1471fd6bab7cc933ce99ed69889366c6f4e9b007/birobirobiro/awesome-shadcn-ui/issues/93]<https://github.com/birobirobiro/awesome-shadcn-ui/issues/93>
Suggestion : Add "shadcn-theme-editor" · Issue #93 · birobirobiro/awesome-shadcn-ui<https://github.com/birobirobiro/awesome-shadcn-ui/issues/93>
github.com

________________________________

**Comment by DavidODonovan** [comment]
@programming-with-ia  - it works! 🎉🎉 It's nice. Thanks and well done.

**Comment by programming-with-ia** [comment]
@DavidODonovan Glad it worked! 🎉 Thanks for the feedback—happy to help!
Please check your email at **david@davidodonovan.com** for a message from **iafullprogrammer@gmail.com**.
Happy coding!
